/* =========================================================
   CONTENT — edit here.
   Projects: add `url` when a site is live, and `image`
   (e.g. 'assets/projects/moto-zona.jpg') to replace the
   generated cover with a real screenshot. `ratio` is the
   screenshot's width / height, so it is shown uncropped.
   ========================================================= */

export const SOCIALS = [
  // { label: 'GitHub', url: 'https://github.com/...' },
  // { label: 'LinkedIn', url: 'https://linkedin.com/in/...' },
  // { label: 'Instagram', url: 'https://instagram.com/...' },
];

export const PROJECTS = [
  {
    name: 'Beauty House',
    domain: 'beautyhousebg.com',
    url: 'https://beautyhousebg.com',
    image: 'assets/projects/beauty-house.jpg',
    ratio: 1600 / 774,
    initials: 'BH',
    pattern: 'dots',
    cat: { en: 'Beauty studio website', bg: 'Сайт за салон за красота' },
    role: { en: 'Design · Development', bg: 'Дизайн · Разработка' },
    tags: ['UI', 'Booking', 'SEO'],
  },
  {
    name: 'moto-zona',
    domain: 'moto-zona.com',
    url: 'https://moto-zona.com',
    image: 'assets/projects/moto-zona.jpg',
    ratio: 1600 / 759,
    initials: 'MZ',
    pattern: 'rings',
    cat: { en: 'Motorcycle marketplace', bg: 'Маркетплейс за мотори' },
    role: { en: 'Founder · Fullstack', bg: 'Основател · Fullstack' },
    tags: ['ASP.NET Core', 'SQL Server', 'Azure'],
  },
  {
    name: 'Stefanovi Cleaning',
    domain: 'stefanovi-cleaning.com',
    url: 'https://stefanovi-cleaning.com',
    image: 'assets/projects/stefanovi-cleaning.jpg',
    ratio: 1600 / 788,
    initials: 'SC',
    pattern: 'wave',
    cat: { en: 'Cleaning company website', bg: 'Сайт за почистваща фирма' },
    role: { en: 'Design · Development', bg: 'Дизайн · Разработка' },
    tags: ['HTML', 'CSS', 'SEO'],
  },
  {
    name: 'Atlantic Drive',
    domain: 'atlanticdrive.bg',
    url: 'https://atlanticdrive.bg',
    image: 'assets/projects/atlantic-drive.jpg',
    ratio: 1600 / 796,
    initials: 'AD',
    pattern: 'grid',
    cat: { en: 'Car dealership platform', bg: 'Платформа за автокъща' },
    role: { en: 'Fullstack · Cloud', bg: 'Fullstack · Cloud' },
    tags: ['.NET', 'SQL', 'Azure'],
  },
  {
    name: 'Floréa',
    domain: 'florea',
    url: '',
    image: '',
    initials: 'Fl',
    pattern: 'petals',
    cat: { en: 'Flower & gift e-shop', bg: 'Онлайн магазин за цветя' },
    role: { en: 'WordPress · WooCommerce', bg: 'WordPress · WooCommerce' },
    tags: ['WooCommerce', 'PHP', 'JS'],
  },
  {
    name: 'PK Lokomotiv GO',
    domain: 'pk-lokomotiv-go',
    url: '',
    image: '',
    initials: 'PK',
    pattern: 'lanes',
    cat: { en: 'Sports club website', bg: 'Сайт за спортен клуб' },
    role: { en: 'Design · Development', bg: 'Дизайн · Разработка' },
    tags: ['UI', 'CMS', 'SEO'],
  },
];

/* ---------------------------------------------------------
   TESTIMONIALS — put REAL client words here.
   Empty `quote` = the card shows a tasteful "coming soon" state.
   --------------------------------------------------------- */
export const TESTIMONIALS = [
  { name: '', role: { en: 'Client', bg: 'Клиент' }, company: 'Atlantic Drive', url: 'https://atlanticdrive.bg', quote: { en: '', bg: '' } },
  { name: '', role: { en: 'Partner', bg: 'Партньор' }, company: 'Crazy Fox Motors', url: '', quote: { en: '', bg: '' } },
  { name: '', role: { en: 'Client', bg: 'Клиент' }, company: 'Stefanovi Cleaning', url: 'https://stefanovi-cleaning.com', quote: { en: '', bg: '' } },
  { name: '', role: { en: 'Client', bg: 'Клиент' }, company: 'Floréa', url: '', quote: { en: '', bg: '' } },
];

/* ---------------------------------------------------------
   FAQ — check the answers match how you actually work.
   --------------------------------------------------------- */
export const FAQ = [
  {
    q: { en: 'How long does a website take?', bg: 'Колко време отнема един сайт?' },
    a: { en: 'A business website usually takes 2–4 weeks. Bigger platforms and online shops are planned in stages, so you see real progress every week.',
         bg: 'Бизнес сайт обикновено отнема 2–4 седмици. По-големите платформи и онлайн магазини ги правим на етапи, така че всяка седмица виждаш реален напредък.' },
  },
  {
    q: { en: 'How much does it cost?', bg: 'Колко струва?' },
    a: { en: "It depends on what you need. Tell me about the project and I'll send you a clear offer — what's included, how long it takes, no hidden extras.",
         bg: 'Зависи какво ти трябва. Разкажи ми за проекта и ще ти пратя ясна оферта — какво влиза, колко време отнема, без скрити екстри.' },
  },
  {
    q: { en: 'Do you handle domain and hosting?', bg: 'Поемаш ли домейн и хостинг?' },
    a: { en: 'Yes. Domain, SSL, hosting on Azure, email setup — I can take care of all of it, or work with what you already have.',
         bg: 'Да. Домейн, SSL, хостинг в Azure, имейли — мога да поема всичко или да работя с това, което вече имаш.' },
  },
  {
    q: { en: 'Can I edit the content myself?', bg: 'Мога ли сам да променям съдържанието?' },
    a: { en: 'Yes. I can build you an admin panel or use WordPress, so you change texts, photos and products on your own — no developer needed.',
         bg: 'Да. Мога да ти направя админ панел или да използвам WordPress — сам сменяш текстове, снимки и продукти, без да викаш програмист.' },
  },
  {
    q: { en: 'What happens after launch?', bg: 'Какво става след пускането?' },
    a: { en: "I don't disappear. Fixes, updates, new features — we agree on support that fits you.",
         bg: 'Не изчезвам. Поправки, ъпдейти, нови функции — договаряме поддръжка, която ти пасва.' },
  },
  {
    q: { en: 'Do you work with clients abroad?', bg: 'Работиш ли с клиенти от чужбина?' },
    a: { en: 'Yes. Everything works remotely — calls, shared designs, live previews. In English or Bulgarian.',
         bg: 'Да. Всичко става дистанционно — разговори, споделени дизайни, live преглед. На български или английски.' },
  },
];

export const I18N = {
  en: {
    'nav.work': 'Work',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.cta': "Let's talk",
    'hero.kicker': 'fullstack developer &amp; freelancer',
    'hero.title': 'Websites, systems &amp; apps — <em>built right.</em>',
    'hero.desc': 'Websites, online shops and custom systems — designed, coded and launched by one person. From the database to the last pixel.',
    'hero.cta1': 'See the work',
    'hero.cta2': 'Start a project',
    'hero.status': 'Available for new projects',
    'hero.location': 'Veliko Tarnovo, BG',
    'hero.scroll': 'Scroll',
    'about.label': 'About',
    'about.text': "I build websites that <em>work for your business</em>: they load fast, look good on every device and bring in real value and real orders.<span class='about__more'>I handle the whole process — from the first conversation to going live and the support after. You have one point of contact who knows your project from start to finish.</span>",
    'about.s1': 'Years in production',
    'about.s2': 'Projects shipped',
    'about.s3': 'Own marketplace, built from zero',
    'work.label': 'Selected work',
    'work.title': 'Work',
    'work.visit': 'Visit',
    'work.soon': 'Coming soon',
    'work.hint': 'Swipe',
    'mcta.status': 'Available for projects',
    'work.cta': 'Your project<br>next?',
    'nav.process': 'Process',
    'proc.label': 'How we work',
    'proc.title': 'Process',
    'proc.aside': 'No surprises. You know what happens at every step — from the first call to launch day.',
    'proc.1.t': 'Conversation',
    'proc.1.d': 'We start by talking: your business, your clients, and what the website has to achieve. We agree on what we build — and why.',
    'proc.1.o': 'Goals &amp; brief',
    'proc.2.t': 'Plan &amp; offer',
    'proc.2.d': 'Page structure, features, timeline and price — all on paper before a single line of code is written.',
    'proc.2.o': 'A clear offer',
    'proc.3.t': 'Design',
    'proc.3.d': 'I design the key pages. You review, comment, and we refine until it is exactly right.',
    'proc.3.o': 'Approved design',
    'proc.4.t': 'Development',
    'proc.4.d': 'I build it — from the database to the last pixel. Every week you get a live preview of the progress.',
    'proc.4.o': 'Live preview',
    'proc.5.t': 'Testing &amp; launch',
    'proc.5.d': 'Phones and desktops, speed, SEO, domain and SSL — all checked. Then we go live.',
    'proc.5.o': 'Website online',
    'proc.6.t': 'Support',
    'proc.6.d': "I don't disappear after launch. Fixes, updates and new features as your business grows.",
    'proc.6.o': 'Long-term partner',
    'services.label': 'What I do',
    'svc.1.t': 'Web apps',
    'svc.1.d': 'Custom platforms on .NET and SQL Server — accounts, dashboards, listings, APIs. Built to handle real traffic.',
    'svc.2.t': 'Websites',
    'svc.2.d': 'Fast, sharp business sites that look great on every screen and actually show up on Google.',
    'svc.3.t': 'E-commerce',
    'svc.3.d': 'Online shops with cart, payments and orders. WooCommerce or fully custom — whatever fits the business.',
    'svc.4.t': 'Cloud',
    'svc.4.d': 'Azure hosting, domains, SSL, CI/CD. Set up once, done right, forgotten about.',
    'testi.label': 'Kind words',
    'testi.title': 'Clients',
    'testi.soon': 'Review on the way',
    'faq.label': 'Questions',
    'faq.note': 'Didn\'t find your question? <a href="#contact" data-scroll-to>Ask me directly →</a>',
    'contact.label': 'Contact',
    'contact.t1': "Let's build",
    'contact.t2': 'something.',
    'contact.sub': 'Got a project, an idea or an offer? Write to me — I answer fast.',
    'contact.btn': 'Write me',
    'form.name': 'Name', 'form.phone': 'Phone', 'form.email': 'Email', 'form.msg': 'What do you need?', 'form.send': 'Send',
    'form.sending': 'Sending…', 'form.ok': 'Thank you! I got your message and will get back to you soon.',
    'form.err': 'Something went wrong. Please try again or write to me by email.',
    'form.title': 'Tell me about your project', 'form.badge': 'I answer fast', 'form.hint': 'Ideally fill in all the fields.', 'form.again': 'Send another message',
    'form.e.name': 'Please enter your name.', 'form.e.contact': 'Leave a phone or an email so I can reach you.', 'form.e.phone': 'The phone number does not look right.',
    'form.e.email': 'The email address does not look right.', 'form.e.message': 'Describe what you need in a few words (at least 10 characters).',
    'footer.time': 'Local time',
    'footer.top': 'Back to top ↑',
    'nav.faq': 'FAQ',
    'hero.l1': 'You bring the idea.',
    'hero.l2': 'I build the',
    'hero.words': ['website', 'online shop', 'platform'],
    'about.s4': 'Layers I cover — DB, API, UI, Cloud',
    'services.title': 'Services',
    'services.aside': 'One developer, the whole stack. No hand-offs, no lost details.',
  },
  bg: {
    'nav.work': 'Проекти',
    'nav.about': 'За мен',
    'nav.services': 'Услуги',
    'nav.contact': 'Контакт',
    'nav.cta': 'Пиши ми',
    'hero.kicker': 'fullstack разработчик и фрийлансър',
    'hero.title': 'Сайтове, системи и приложения — <em>направени както трябва.</em>',
    'hero.desc': 'Сайтове, онлайн магазини и системи по поръчка — проектирани, написани и пуснати от един човек. От базата данни до последния пиксел.',
    'hero.cta1': 'Виж проектите',
    'hero.cta2': 'Започни проект',
    'hero.status': 'Свободен за нови проекти',
    'hero.location': 'Велико Търново, BG',
    'hero.scroll': 'Надолу',
    'about.label': 'За мен',
    'about.text': 'Създавам сайтове, които <em>работят за бизнеса ти</em>: зареждат бързо, изглеждат добре на всяко устройство и носят стойност и реални поръчки.<span class="about__more">Поемам целия процес — от първия разговор до пускането онлайн и поддръжката след това. Имаш един човек за контакт, който познава проекта ти от началото до края.</span>',
    'about.s1': 'Години реален опит',
    'about.s2': 'Пуснати проекта',
    'about.s3': 'Собствен маркетплейс, от нулата',
    'work.label': 'Избрани проекти',
    'work.title': 'Проекти',
    'work.visit': 'Виж',
    'work.soon': 'Очаквай скоро',
    'work.hint': 'Плъзни',
    'mcta.status': 'Свободен за проекти',
    'work.cta': 'Твоят проект<br>е следващ?',
    'nav.process': 'Процес',
    'proc.label': 'Как работим',
    'proc.title': 'Процес',
    'proc.aside': 'Без изненади. Знаеш какво се случва на всяка стъпка — от първия разговор до пускането.',
    'proc.1.t': 'Разговор',
    'proc.1.d': 'Започваме с разговор: какъв е бизнесът ти, кои са клиентите ти и какво трябва да постигне сайтът. Уточняваме какво ще правим — и защо.',
    'proc.1.o': 'Цели и бриф',
    'proc.2.t': 'План и оферта',
    'proc.2.d': 'Структура на страниците, функции, срокове и цена — всичко е ясно, преди да е написан и ред код.',
    'proc.2.o': 'Ясна оферта',
    'proc.3.t': 'Дизайн',
    'proc.3.d': 'Правя дизайна на ключовите страници. Преглеждаш, коментираш и го донастройваме, докато стане точно както трябва.',
    'proc.3.o': 'Одобрен дизайн',
    'proc.4.t': 'Разработка',
    'proc.4.d': 'Изграждам сайта — от базата данни до последния пиксел. Всяка седмица виждаш live преглед на напредъка.',
    'proc.4.o': 'Live преглед',
    'proc.5.t': 'Тестове и пускане',
    'proc.5.d': 'Телефон и компютър, скорост, SEO, домейн и SSL — всичко е проверено. След това пускаме сайта.',
    'proc.5.o': 'Сайтът е онлайн',
    'proc.6.t': 'Поддръжка',
    'proc.6.d': 'Не изчезвам след пускането. Поправки, ъпдейти и нови функции, когато бизнесът порасне.',
    'proc.6.o': 'Дългосрочен партньор',
    'services.label': 'С какво се занимавам',
    'svc.1.t': 'Уеб приложения',
    'svc.1.d': 'Платформи по поръчка на .NET и SQL Server — профили, админ панели, обяви, API. Издържат на реален трафик.',
    'svc.2.t': 'Сайтове',
    'svc.2.d': 'Бързи и изчистени бизнес сайтове, които стоят страхотно на всеки екран и реално се намират в Google.',
    'svc.3.t': 'Магазини',
    'svc.3.d': 'Онлайн магазини с количка, плащане и поръчки. С WooCommerce или изцяло по поръчка — каквото пасва на бизнеса.',
    'svc.4.t': 'Cloud',
    'svc.4.d': 'Хостинг в Azure, домейни, SSL, CI/CD. Настройва се веднъж, както трябва, и забравяш за него.',
    'testi.label': 'Добри думи',
    'testi.title': 'Клиенти',
    'testi.soon': 'Отзивът идва скоро',
    'faq.label': 'Въпроси',
    'faq.note': 'Не намери въпроса си? <a href="#contact" data-scroll-to>Питай ме директно →</a>',
    'contact.label': 'Контакт',
    'contact.t1': 'Да направим',
    'contact.t2': 'нещо яко.',
    'contact.sub': 'Имаш проект, идея или предложение? Пиши ми — отговарям бързо.',
    'contact.btn': 'Пиши ми',
    'form.name': 'Име', 'form.phone': 'Телефон', 'form.email': 'Имейл', 'form.msg': 'Какво ти трябва?', 'form.send': 'Изпрати',
    'form.sending': 'Изпращам…', 'form.ok': 'Благодаря! Получих съобщението ти и ще се свържа с теб скоро.',
    'form.err': 'Нещо се обърка. Опитай пак или ми пиши на имейла.',
    'form.title': 'Разкажи ми за проекта', 'form.badge': 'Отговарям бързо', 'form.hint': 'Желателно е да попълниш всички полета.', 'form.again': 'Изпрати ново съобщение',
    'form.e.name': 'Моля, напиши името си.', 'form.e.contact': 'Остави телефон или имейл, за да се свържа с теб.', 'form.e.phone': 'Телефонният номер не изглежда правилен.',
    'form.e.email': 'Имейл адресът не изглежда правилен.', 'form.e.message': 'Опиши с няколко думи какво ти трябва (поне 10 символа).',
    'footer.time': 'Местно време',
    'footer.top': 'Нагоре ↑',
    'nav.faq': 'Въпроси',
    'hero.l1': 'Ти даваш идеята.',
    'hero.l2': 'Аз създавам',
    'hero.words': ['сайта', 'магазина', 'платформата'],
    'about.s4': 'Слоя, които покривам — DB, API, UI, Cloud',
    'services.title': 'Услуги',
    'services.aside': 'Един разработчик, целият стек. Без прехвърляне между хора, без изгубени детайли.',
  },
};
